<?php

namespace Boot\Foundation\Bootstrappers;

use App\Providers\ServiceProvider;

class LoadServiceProviders extends Bootstrapper
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $app = $this->app;
        $providers = config('app.providers');

        if ($app->bootedViaHttpRequest())
        {
            $providers = [...$providers, \App\Providers\RouteServiceProvider::class];
        } elseif ($app->bootedViaConsole())
        {
            $providers = [...$providers, \App\Providers\ConsoleServiceProvider::class];
        }

        ServiceProvider::setup($app, $providers);
    }
}