<?php

namespace Boot\Foundation\Bootstrappers;

use App\Providers\ServiceProvider;

class LoadServiceProviders extends Bootstrapper
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        ServiceProvider::setup($this->app, (array)config('app.providers'));
    }
}